CREATE OR REPLACE VIEW FUSIONT.FUSION_VW_ENDERECO_ALTER AS
SELECT
    '0' AS COD_PRACA_ERP,
    LE.UFENTREGA AS UF,
    CI.DESCRCIDADE AS CIDADE,
    LE.BAIRROENTREGA AS BAIRRO,
    LE.ENDERECOENTREGA AS
END,
  LE.NUMERO AS NUM_END,
  LE.CEPENTREGA AS CEP,
  COALESCE(LE.OBSERVACAO, '') AS REF_ENTREGA,
  'N' AS SN_PADRAO,
  COALESCE(NULLIF(TRIM(LE.LATITUDE), ''), '1000') AS LATITUDE,
  COALESCE(NULLIF(TRIM(LE.LONGITUDE), ''), '1000') AS LONGITUDE,
  LE.IDLOCALENTREGA AS COD_END_ERP,
  LE.IDCLIFOR AS CLI_FK_680
FROM
DBA.LOCAL_ENTREGA LE
JOIN DBA.CIDADES_IBGE CI
  ON
CI.IDCIDADE = LE.IDCIDADE_ENTREGA;
