-- FUSIONT.FUSION_VW_ENTREGA_ITEM

CREATE OR REPLACE VIEW FUSIONT.FUSION_VW_ENTREGA_ITEM AS
SELECT
    IDPLANILHA,
    IDEMPRESA,
    NUMSEQUENCIA,
    IDPRODUTO || '@' || IDSUBPRODUTO AS MERC_PF_687,
    QTDPRODUTO AS QTD_COMER_687,
    VALUNITBRUTO AS PRC_COMER_687,
    COALESCE(VALICMSUBST, 0) AS VLR_ST,
    COALESCE(VARCHAR(IDSITTRIB), '00') AS CST_LIST_NF_57
FROM
    DBA.ESTOQUE_ANALITICO
WHERE
    NUMSEQUENCIA > 0;