-- FUSIONT.FUSION_VW_PRODUTO

CREATE OR REPLACE VIEW FUSIONT.FUSION_VW_PRODUTO AS
SELECT
    P.IDPRODUTO AS MERC_PK_461,
    P.DESCRCOMPRODUTO AS DESCRICAO,
    P.EMBALAGEMSAIDA AS UNID_COMER_461,
    COALESCE(NULLIF(TRIM(PG.NCM), ''), '0') AS NCM_FK_461,
    COALESCE(P.FABRICANTE, '0') AS REF_FABRIC,
    '.' AS DEFIN_MERC_461,
    '.' AS FOTO_461,
    COALESCE(P.IDSUBGRUPO, 0) AS FAMILIA_FK_461,
    '0' AS CONTA_291,
    '.' AS DESCR_291,
    PPP.IDEMPRESA AS EMPRESA_PF_468,
    COALESCE(PPP.VALPRECOVAREJO, 0) AS PRC_COMER_468,
    COALESCE(SALDO.QTDATUALESTOQUE, 0) AS SALDO,
    'A' AS MERC_FUNCIO_468,
    '0' AS FABRIC_PF_478,
    '.' AS DESCR_271,
    '0' AS GRUPO_FABRIC_FK_271,
    '.' AS FAMILIA_COMIS_MERC_FK_468,
    '0' AS DESCR_286,
    COALESCE(PPP.VALCUSTOREPOS, 0) AS CUSTO_COMPRA_468,
    '.' AS FATORSTPRODUTO,
    '.' AS CLASSE_MERC_468,
    'S' AS ENVIA_POCKET_461,
    '.' AS LISTA_EMB_BLOQS
FROM
    DBA.POLITICA_PRECO_PRODUTO PPP
INNER JOIN DBA.PRODUTO_GRADE PG
  ON
    PG.IDPRODUTO = PPP.IDPRODUTO
    AND PG.IDSUBPRODUTO = PPP.IDSUBPRODUTO
INNER JOIN DBA.PRODUTO P
  ON
    P.IDPRODUTO = PG.IDPRODUTO
LEFT JOIN (
    SELECT
        ESA.IDEMPRESA,
        ESA.IDPRODUTO,
        ESA.IDSUBPRODUTO,
        SUM(ESA.QTDATUALESTOQUE) AS QTDATUALESTOQUE
    FROM
        DBA.ESTOQUE_SALDO_ATUAL ESA
    INNER JOIN DBA.ESTOQUE_CADASTRO_LOCAL ECL
    ON
        ECL.IDLOCALESTOQUE = ESA.IDLOCALESTOQUE
        AND ECL.FLAGDISPONVENDA = 'T'
    GROUP BY
        ESA.IDEMPRESA,
        ESA.IDPRODUTO,
        ESA.IDSUBPRODUTO
) SALDO
  ON
    SALDO.IDEMPRESA = PPP.IDEMPRESA
    AND SALDO.IDPRODUTO = PPP.IDPRODUTO
    AND SALDO.IDSUBPRODUTO =
      CASE
        WHEN P.TIPOBAIXAMESTRE = 'M' THEN P.IDPRODUTO
        ELSE PPP.IDSUBPRODUTO
    END
WHERE
    COALESCE(PG.FLAGINATIVO, 'F') = 'F'
    AND COALESCE(PG.FLAGBLOQUEIAVENDA, 'F') = 'F';